### ISSUE TITLE
Trojan Horse detected to the file

### ISSUE THREAD

**Issue by ZyrusplaysAnimations** [imageny/VFProxy#3]
I scanned the file to virustotal and detected a trojan to the VFproxyfile. 

Name of trojan: **Trojan.Malware.300983.susgen**

I unzipped the file into my computer before I scanned it to virustotal. After I know there is a virus, I delete the file and I conduct a full scan in my computer.

Thank you.

**Comment by cantstandya-gh** [comment]
Hello,
This is CLEARLY a false positive. All it does is generate a fake email address which is used to admit in to the VoiceForge API.

**Comment by ZyrusplaysAnimations** [comment]
Ok. Thank you.
